version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: money_mate_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/logs
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U money_mate -d money_mate_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  #pgadmin
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: money_mate_pgadmin
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_EMAIL}
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin  # persists pgadmin config
#      - ./logs/pgadmin:/logs
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "5"
  # Django Web App
  web:
    build: .
    container_name: money_mate_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000
            gunicorn --bind 0.0.0.0:8000 your_project.wsgi:application"
    volumes:
      - .:/app
      - ./logs:/logs
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      PYTHONUNBUFFERED: '1'
    depends_on:
      db:
        condition: service_healthy

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  postgres_data:
#  pgadmin_data: