apiVersion: v1
kind: ConfigMap
metadata:
  name: money-mate-config
  namespace: money-mate
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  DATABASE_HOST: "127.0.0.1"
  DATABASE_PORT: "5432"