apiVersion: v1
kind: Secret
metadata:
  name: money-mate-secrets
  namespace: money-mate
type: Opaque
stringData:
  SECRET_KEY: "(t&(9(rqnl8xibfzo91m3hp=x^^q$a0+s^p7ghrc9n)m$b-6yf"
  DATABASE_NAME: "money_mate_db"
  DATABASE_USER: "money_mate"
  DATABASE_PASSWORD: "dijkstra_123"