# Generated by Django 5.2.15 on 2026-06-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user_model',
        ),
    ]
