# Generated by Django 5.1.2 on 2026-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='opening_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
