"""
Django settings for money_mate_django project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set default values and casting
    DEBUG=(bool, False)
)

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
# It automatically reads a comma-separated string and casts it to a Python list!
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])
# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninja_extra',
    'ninja_jwt',
    'corsheaders', # Add this before other middleware apps (see next step)
    'oauth2_provider',
    'rest_framework',
    #App modules
    'loginModule',
    'workbook'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Should be as high as possible
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'money_mate_django.urls' #'money_mate_django.urls'

CORS_ALLOWED_ORIGINS = [
    "https://your-frontend-domain.com",
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    "http://localhost:8000", # For local development
]
CORS_ALLOW_CREDENTIALS = True

WSGI_APPLICATION = 'money_mate_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,  # This MUST be True for admin to work
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'loginModule.UserModel'

# Telling Django REST Framework to use OAuth2 Authentication
# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Defining the scopes available for API
OAUTH2_PROVIDER = {
    'SCOPES': {
        'read': 'Read access to protected resources',
        'write': 'Write access to protected resources',
        'admin': 'Admin access',
    },
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,  # 10 hours
    'REFRESH_TOKEN_EXPIRE_SECONDS': 2592000,  # 30 days
}

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'https://yourdomain.com',  # for production
]
# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Redirect after login/logout for admin page
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


ENABLE_LOGGING = env.bool('ENABLE_LOGGING', default=True)
LOG_LEVEL = env.str('LOG_LEVEL', default='INFO')

# Creating a variable for logs directory to keep the code clean
LOG_DIR = BASE_DIR / 'logs'

if ENABLE_LOGGING:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{levelname} {asctime} [{name}] {message}',
                'style': '{',
            },
        },
        'handlers': {
            # Pointing this to the custom class for money_mate_django/log_handlers.py
            'dynamic_router': {
                'level': LOG_LEVEL,
                'class': 'money_mate_django.log_handlers.DynamicFileHandler',
                'log_dir': LOG_DIR,
                'formatter': 'verbose',
            },
        },
        'loggers': {
            # We use the empty string '' to catch ALL logs globally (the root logger)
            '': {
                'handlers': ['dynamic_router'],
                'level': LOG_LEVEL,
            },
            # silencing noisy dependencies:
            'django.utils.autoreload': {
                'level': 'WARNING',
            },
            'django.server': {
                'handlers': [],  # Empty handlers forces it to look at the parent ('')
                'level': LOG_LEVEL,
                'propagate': True,
            },

            'django.db.backends': {
                'handlers': [],
                'level': LOG_LEVEL,
                'propagate': True,
            },
        },
    }
else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,
        'handlers': {'null': {'class': 'logging.NullHandler'}},
        'loggers': {'': {'handlers': ['null'], 'level': 'CRITICAL'}}
    }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'


STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
